### PR TITLE
Create ru_ru.json

### PR DESCRIPTION
**Pull request by fantom2010**

### CODE REVIEW

**Comment by linxuanm** [comment]
The `master` branch is for 1.12.2, which uses the `.lang` format, and already has a Russian localization. I think you meant to merge into 1.13+ branches?.

**Comment by fantom2010** [comment]
This is the Russian translation for version 1.15.2

**Comment by linxuanm** [comment]
You are merging into 1.12.2 at the moment. The source for 1.15.2 is on the `1.15.2` branch.
Alternatively I can create your posted Russian translation locally and push into `1.15.2`.

Thanks for the contribution!

**Comment by linxuanm** [comment]
The Russian translation has been added in [this commit](https://github.com/davidmaamoaix/TinyMobFarm/commit/52c77d586bcbc8d064244669f4b9ab8e1b1360cb).

**Pull request closed without merging**
